name: Deploy Almanach

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy on VPS
        run: |
          cp ./scripts/deploy.sh /opt/almanach/scripts/deploy.sh
          /opt/almanach/scripts/deploy.sh
